flower_board_api_getbyproject:
    path:     /project/{projectId}
    defaults: { _controller: FlowerBoardBundle:Api\Board:getByProject }

flower_board_api_getbyaccount:
    path:     /account/{accountId}
    defaults: { _controller: FlowerBoardBundle:Api\Board:getByAccount }

flower_board_api_getone:
    path:     /{id}
    defaults: { _controller: FlowerBoardBundle:Api\Board:getById }

flower_board_api_getall:
    path:     /
    defaults: { _controller: FlowerBoardBundle:Api\Board:getAll }

flower_tast_status_api_getall:
    path:     /taskstatus/getall
    defaults: { _controller: FlowerBoardBundle:Api\TaskStatus:getAll }
