services:

    form.type.task:
        class: Flower\BoardBundle\Form\Type\TaskType
        arguments: ["@security.context"]
        tags:
            - { name: form.type, alias: task_type }

    form.type.task_quick:
            class: Flower\BoardBundle\Form\Type\TaskQuickType
            arguments: ["@security.context"]
            tags:
                - { name: form.type, alias: task_type }


    board.repository.history:
        class: Doctrine\ORM\EntityRepository
        factory: [@doctrine.orm.entity_manager, getRepository]
        arguments:
            - Flower\ModelBundle\Entity\Board\History

    board.service.task:
        class: Flower\BoardBundle\Service\TaskService
        calls:
            - [setContainer, ["@service_container"]]

    board.service.history:
        class: Flower\BoardBundle\Service\HistoryService
        arguments: ['@board.repository.history', '@translator', '@user.service.securitygroup', '@user.service.orgposition', '@router']

    board.service.report:
        class: Flower\BoardBundle\Service\ReportService
        calls:
            - [setContainer, ["@service_container"]]

