<?php

namespace Flower\BoardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BoardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardRepository extends EntityRepository
{
	public function getCountTodo()
    {
        $qb = $this->createQueryBuilder("b");
        $qb->select("COUNT(b)");
        //$qb->innerJoin("t.status", "s", Join::WITH, 's.name = :status_name')->setParameter("status_name", TaskStatus::STATUS_TODO);
        return $qb->getQuery()->getSingleScalarResult();
    }

}
