<?php

namespace Flower\BoardBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Flower\ModelBundle\Entity\Board\TaskStatus;

/**
 * TaskStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskStatusRepository extends EntityRepository
{

    public function getKanbanStatuses()
    {
        $qb = $this->createQueryBuilder("ts");
        $qb->where("ts.name = :name1")->setParameter("name1", TaskStatus::STATUS_TODO);
        $qb->orWhere("ts.name = :name2")->setParameter("name2", TaskStatus::STATUS_DOING);
        $qb->orWhere("ts.name = :name3")->setParameter("name3", TaskStatus::STATUS_DONE);

        return $qb->getQuery()->getResult();
    }

}
