<?php

namespace Flower\BoardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskAttachmentRepository extends EntityRepository
{


}
