<?php

namespace Flower\BoardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskFilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskFilterRepository extends EntityRepository
{


}
