<?php

namespace Flower\BoardBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Flower\ModelBundle\Entity\Board\Task;
/**
 * TimeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeLogRepository extends EntityRepository
{
    public function getSpentByTask(Task $task)
    {
        $qb = $this->createQueryBuilder("tl");
        $qb->select("SUM(tl.hours)");
                
        $qb->andWhere("tl.task = :task")->setParameter("task", $task);
        
        return $qb->getQuery()->getSingleScalarResult();
    }
    
    /* Returns sum of all hours */
    public function getAllSpent()
    {
        $qb = $this->createQueryBuilder("tl");
        $qb->select("SUM(tl.hours)");
        
        return $qb->getQuery()->getSingleScalarResult();
    }

    /* Returns sum of all hours */
    public function getSpent(Task $task = null, User $user = null)
    {
        $qb = $this->createQueryBuilder("tl");
        $qb->select("SUM(tl.hours)");
        if($task){
        	$qb->where("tl.task = :task")->setParameter("task", $task);
        }
        if($user){
        	$qb->andWhere("tl.user = :user")->setParameter("user", $user);
        }

        return $qb->getQuery()->getSingleScalarResult();
    }
}
